// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(HomeEconomicsDbContext))]
    [Migration("20260118101947_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.MovementMonth.MonthMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MovementMonthId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovementMonthId", "Type", "Paid");

                    b.ToTable("MonthMovements", (string)null);
                });

            modelBuilder.Entity("Domain.MovementMonth.MovementMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("MovementMonths", (string)null);
                });

            modelBuilder.Entity("Domain.MovementMonth.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("MovementMonthId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovementMonthId", "Day")
                        .IsDescending(false, true);

                    b.ToTable("Statuses", (string)null);
                });

            modelBuilder.Entity("Domain.Movements.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Months")
                        .IsRequired()
                        .HasMaxLength(23)
                        .HasColumnType("character varying(23)");

                    b.Property<int>("MovementId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovementId")
                        .IsUnique();

                    b.ToTable("Frequencies", (string)null);
                });

            modelBuilder.Entity("Domain.Movements.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("Domain.MovementMonth.MonthMovement", b =>
                {
                    b.HasOne("Domain.MovementMonth.MovementMonth", null)
                        .WithMany("_monthMovements")
                        .HasForeignKey("MovementMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MovementMonth.Status", b =>
                {
                    b.HasOne("Domain.MovementMonth.MovementMonth", null)
                        .WithMany("_statuses")
                        .HasForeignKey("MovementMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Movements.Frequency", b =>
                {
                    b.HasOne("Domain.Movements.Movement", null)
                        .WithOne("Frequency")
                        .HasForeignKey("Domain.Movements.Frequency", "MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MovementMonth.MovementMonth", b =>
                {
                    b.Navigation("_monthMovements");

                    b.Navigation("_statuses");
                });

            modelBuilder.Entity("Domain.Movements.Movement", b =>
                {
                    b.Navigation("Frequency")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
