# Use postgres/example user/password credentials
services:
  homeeconomics:
    build:
      context: .
      dockerfile: src/HomeEconomics/Dockerfile
    ports:
      - "6001:6001"
    environment:
      - ConnectionStrings__HomeEconomics=Host=postgres;Port=5432;Database=homeeconomics;Username=homeeconomics;Password=homeeconomics
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=homeeconomics
      - POSTGRES_USER=homeeconomics
      - POSTGRES_PASSWORD=homeeconomics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
