# Use postgres/example user/password credentials
services:
  homeeconomics:
    build:
      context: .
      dockerfile: src/HomeEconomics/Dockerfile
    ports:
      - "6001:6001"
    environment:
      - ConnectionStrings__HomeEconomics=${HOMEECONOMICS_CONNECTION_STRING}
    restart: unless-stopped
