name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master

pool:
  vmImage: "windows-2019"

variables:
  - group: HomeEconomics

stages:
  - stage: build_and_publish_artifacts
    displayName: Build and publish artifacts

    jobs:
      - job: build_publish_artifacts
        displayName: Build and publish artifacts

        steps:

          - task: UseNode@1
            displayName: "Use node LTS"
            inputs:
              version: '14.15.1'

          - task: UseDotNet@2
            displayName: "Use global.json dotnet version"
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: "restore"
              projects: "**/*.csproj"
              feedsToUse: "select"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: "build"
              projects: "**/*.csproj"
              arguments: "--no-restore -c Release"

          - task: DockerCompose@0
            displayName: "docker-compose up"
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'DockerHub'
              dockerComposeFile: '**/docker-compose.yaml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'up -d'

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: "test"
              arguments: '--no-restore -c Release --collect "XPlat Code coverage"'
              publishTestResults: false
              
          - task: DockerCompose@0
            displayName: "docker-compose down"
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'DockerHub'
              dockerComposeFile: '**/docker-compose.yaml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'down'

          - script: "dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8"
            displayName: "Install ReportGenerator tool"

          - script: 'reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'
            displayName: "Create reports"

          - task: PublishCodeCoverageResults@1
            displayName: "Publish code coverage"
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml"

          - task: DotNetCoreCLI@2
            displayName: "dotnet publish"
            inputs:
              command: publish
              publishWebProjects: true
              arguments: '--no-restore --no-build -c Release -o $(Build.ArtifactStagingDirectory)\HomeEconomics'
              modifyOutputPath: false
              zipAfterPublish: false

          - task: CopyFiles@2
            displayName: "Copy SPA to ArtifactStagingDirectory"
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\HomeEconomics\spa'
              Contents: "**"
              TargetFolder: '$(Build.ArtifactStagingDirectory)\spa'
              CleanTargetFolder: true

          - task: Npm@1
            displayName: "npm ci"
            inputs:
              command: "install"
              workingDir: '$(Build.ArtifactStagingDirectory)\spa'

          # - task: Npm@1
          #   displayName: 'npm test'
          #   inputs:
          #     command: 'custom'
          #     workingDir: '$(Build.ArtifactStagingDirectory)\spa'
          #     customCommand: 'run citest'

          - task: Npm@1
            displayName: "npm build"
            inputs:
              command: "custom"
              workingDir: '$(Build.ArtifactStagingDirectory)\spa'
              customCommand: "run build"

          - task: CopyFiles@2
            displayName: "Copy SPA build into HomeEconomics artifact"
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)\spa\build'
              Contents: "**"
              TargetFolder: '$(Build.ArtifactStagingDirectory)\HomeEconomics\wwwroot'
              CleanTargetFolder: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish build artifact"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)\HomeEconomics'
              ArtifactName: "HomeEconomics"
              publishLocation: "Container"

  - stage: deploy_infrastructure_and_upload_zip
    displayName: Deploy infrastructure and upload HomeEconomics zip

    jobs:
      - job: deploy_infrastructure_and_upload_zip
        displayName: Deploy infrastructure and upload HomeEconomics zip

        steps:
          - download: current
            displayName: "Download HomeEconomics artifact"
            artifact: HomeEconomics

          - task: TerraformInstaller@0
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "$(terraformVersion)"

          - task: TerraformTaskV1@0
            displayName: "Terraform init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'pipeline/infrastructure'
              backendServiceArm: 'HomeEconomics'
              backendAzureRmResourceGroupName: 'Shared'
              backendAzureRmStorageAccountName: 'tfstatesst'
              backendAzureRmContainerName: 'homeeconomics'
              backendAzureRmKey: 'tf/terraform.tfstate'

          - task: TerraformTaskV1@0
            displayName: "Terraform apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: 'pipeline/infrastructure'
              commandOptions: '-var subscriptionId=$(subscriptionId) -var sqlServerAdministratorLogin=$(sqlServerAdministratorLogin) -var sqlServerAdministratorPassword=$(sqlServerAdministratorPassword)'
              environmentServiceNameAzureRM: 'HomeEconomics'

          - task: terraform-outputs@0
            displayName: "Terraform Outputs"
            inputs:
              workingDirectory: "pipeline/infrastructure"
              mapSensitiveOutputsAsSecrets: true

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: "Replace tokens in appsettings.json"
            inputs:
              rootDirectory: "$(Pipeline.Workspace)/HomeEconomics"
              targetFiles: appsettings.json
              actionOnMissing: fail
              tokenPrefix: "%%"
              tokenSuffix: "%%"

          - task: CopyFiles@2
            displayName: "Add install script"
            inputs:
              Contents: "RunHomeEconomicsService.bat"
              TargetFolder: "$(Pipeline.Workspace)/HomeEconomics"

          - task: ArchiveFiles@2
            displayName: "Archive HomeEconomics"
            inputs:
              rootFolderOrFile: "$(Pipeline.Workspace)/HomeEconomics"
              includeRootFolder: false
              archiveFile: "$(Pipeline.Workspace)/HomeEconomics.zip"

          - task: AzureFileCopy@2
            displayName: "Copy HomeEconomics artifact to storage"
            inputs:
              SourcePath: '$(Pipeline.Workspace)/HomeEconomics.zip'
              azureSubscription: 'HomeEconomics'
              Destination: 'AzureBlob'
              storage: 'artifactsst'
              ContainerName: 'homeeconomics'
